import { NextAuthProvider } from "./providers";
import React from "react";
import Head from "@/app/Head";
import "@/app/globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: { children: React.ReactNode; }) {
    return (
        <html lang="en">
            <Head />
            <body>
                <NextAuthProvider>
                    {children}
                </NextAuthProvider>
            </body>
        </html>
    );
}
