import './globals.css'
import {ReactNode} from "react";
import Header from "@/app/header";
import Head from "@/app/head";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

// TODO: next-auth 도입 후 Session 객체를 확인하여 유효한 세션인지 확인해야 함
const checkSessionIsValid = (session: boolean) => {
    return session
}

export default function RootLayout({children,}: { children: ReactNode }) {
    // TODO: next-auth 도입 후 현제 사용자의 세션을 불러와야 함
    const session = true;

    return (
        <html lang="en">
            <Head />
            <body className="h-screen w-full flex flex-col">
                {checkSessionIsValid(session) ? <Header/> : null}
                {children}
            </body>
        </html>
    )
}

